name: Node.js CI

on:
  push:
    branches: [ "teste-1" ]
  pull_request:
    branches: [ "teste-1" ]

jobs:
  build:

    runs-on: self-hosted


    steps:
      - name: Clone Repositório
        uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18.X
          cache: 'npm'
      - name: CI APP
        run: |
          npm i
          npm run build
      - name: CD FRONT
        run: |
          export atual=$(pwd)
          cd /var/www/html
          sudo rm -r * 
          cd $atual/dist
          sudo cp -r * /var/www/html
